import pls21 from '../images/fulls/pls21.jpg'
import morganstanley from '../images/fulls/morganstanley.png'
import ucdavis from '../images/fulls/ucdavis2.png'
import dbc from '../images/fulls/devbootcamp.png'

export default function() {
	return [
		{ image: pls21, title: 'Applications of Computers and Technology, Teaching Assistant', desc: "One of my favorite experiences as a UC Davis undergraduate was working as a teaching assistant for a computer software course. As a teaching assistant, I developed my own lesson plans, managed other staff members, and taught in front of up to 50 students at a time. I'm so grateful that I had the opportunity to work as a teaching assistant because it really helped me overcome my fear of public speaking, consistently pushed me out of my comfort zone, and truly helped me grow as an individual." },
		{ image: morganstanley, title: 'Global Wealth Management Finance Intern', desc: "For a period of three months, I interned under Morgan Stanley's Vice President of Global Wealth Management in Sacramento. During my internship, I anaylzed various market sectors and then conducted stock pitches on the sectors and companies that I believed would perform best for a particular quarter. I learned how one of Morgan Stanley's top financial advisors approached portfolio management, retirement services, and how MS applied different investment strategies in order to minimize risk and raise capital for their clients." },
		{ image: ucdavis, title: 'University of California, Davis Graduate', desc: "Studying at UC Davis improved my ability to effectively manage my time between studying, working, all while trying to maintain a social life. These experiences really showed me the importance not taking anything for granted and making every second of the day count. My undergraduate experience at UC Davis had a huge impact on my life, and I'm truly grateful for being able to attend such an amazing school."},
		{ image: dbc, title: 'Dev Bootcamp Graduate', desc: "I gained and learned so many skills during my experience at DBC. The program really showed me how to approach programming problems effectively. It also improved my ability to research and anaylze problems through multiple approaches before finally determining which solution would be most optimal for the problem at hand. Through DBC, I learned the importance of applying best practices and programming conventions within the industry-- From utilizing proper git workflow, and appyling agile methodologies when collaborating in groups, to the importance of implementing a strong testing suite and being able to write code that other programmers could understand and contribute to."}
	]
}